steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - devopstesting2
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python38
  - --allow-unauthenticated
